"""
MÓDULOS EM PYTHON SÃO ARQUIVOS PYTHON COM A EXTENSÃO .py QUE IMPLEMENTAM UM CONJUNTO DE FUNÇÕES 
IMPORTAMOS O MÓDULO EM NOSSO SCRIPT USANDO O COMANDO IMPORT

ex:
    import math

A PRIMEIRA VEZ QUE UM MÓDULO É CARREGASO EM SCRIPT PYTHON ELE É
INICIALIZADO E FICA DISPONÍVEL PARA USO.

UM MÓDULO SÓ PRECISA SER IMPORTADO UMA VEZ NO CÓDIGO.

ESCREVER MÓDULOS PYTHON É MUITO SIMPLES. PARA CRIAR UM MÓDULO DE 
SUA PREFERENCIA, BASTA CRIAR UM NOVO ARQUIVO .py COM O NOME DO MÓDULO
E, EM SEGUIDA, IMPORTÁ - LO UTILIZANDO O COMANDO DE IMPORTAÇÃO.

ex: 
    meu_modulo.py
    import"meu_modulo"

TAMBÉM É POSSÍVEL IMPORTAR FUNÇÕES ESPECIFICAS DE UM MÓDULO

#importando a função sqrt do módulo math
from math import sqrt

ISSO ECONOMIZA MEMORIA

"""

''' 

PACOTES SÃO UMA FORMA DE ESTRUTURAR OS MÓDULOS EM PYTHON

import modulo
import pacote.modulo

UM PACOTE É UM CONJUNTO DE MODULOS PYTHON

ENQUANTO UM MÓDULO É UM ÚNICO ARQUIVO PYTHON, UM PACOTE É UM DIRETÓRIO
DE MÓDULOS PYTHON CONTENDO UM ARQUIVO __init__.py



'''